### ISSUE TITLE
Build does not find bibiservabstraction

### ISSUE THREAD

**Issue by pbelmann** [BiBiServ/bibiserv#22]
The current ci run returns the following error:

https://circleci.com/gh/BiBiServ/bibiserv/10

It seems that it cannot find the bibiservabstraction libs.

@jkrue  suggested to remove the submodule version numbers.

**Comment by pbelmann** [comment]
By upgrading maven 3.0.x to 3.3.x maven seems to find the libraries, but it fails on parsing the remote xml:

~~~
[INFO] --- maven-dependency-plugin:2.10:properties (default) @ bibiservabstraction ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ bibiservabstraction ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 0 resource
[INFO] 
[INFO] --- jaxb2-maven-plugin:2.2:xjc (xjc) @ bibiservabstraction ---
[WARNING] Configured encoding [UTF-8]?differs from encoding given in system property 'file.encoding' [ANSI_X3.4-1968]
[ERROR] http://bibiserv.techfak.uni-bielefeld.de/xsd/bibiserv2/xml.xsd [1,50] 
org.xml.sax.SAXParseException; systemId: http://bibiserv.techfak.uni-bielefeld.de/xsd/bibiserv2/xml.xsd; lineNumber: 1; columnNumber: 50; White spaces are required between publicId and systemId.
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
        at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1472)
        at com.sun.org.apache.xerces.internal.impl.XMLScanner.scanExternalID(XMLScanner.java:1072)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.scanDoctypeDecl(XMLDocumentScannerImpl.java:642)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:924)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)

~~~

**Comment by pbelmann** [comment]
with PR #23 I added configuration for building the bibiserv on circle ci.
Maven depends on version >= 3.3.9 which is also documented in the README. 
However the tests are still not executed. We should create issues for fixing the tests.
